on:
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      # checkout
      - uses: actions/checkout@v3 # should be a sha, but eh
      # activate go
      - uses: actions/setup-go@v4
      - name: tests
        run: go test ./... -v