on:
  repository_dispatch:
    types: [dispatch_test]

jobs:
  echo_body:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: '${{toJSON(github.event.client_payload)}}'
    steps:
      - run: echo $PAYLOAD
