on:
  repository_dispatch:
    types: [dispatch_test]

jobs:
  echo_body:
    runs-on: ubuntu-latest
    env:
      PAYLOAD: '${{toJSON(github.event.client_payload)}}'
    steps:
      - name: foo
        run: |
          echo "${{github.event.client_payload.sha}}"
          echo "${{github.event.client_payload.repo}}"

#  {
#    "event_type": "plugin_update_event",
#    "client_payload": {
#        "sha":"abcdef",
#        "repo":"vault-plugin-database-snowflake"
#    }
#  }